WebKhameela/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, re_path, include
from profilemela.views import signup as signup
from profilemela.views import portfolio as portfolio
from profilemela.views import homepage as homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('signup', signup, name="sign up"),
    re_path('portfolio', portfolio, name="portfolio"),
    re_path('home', homepage, name="home"),
    path('', include('story5.urls')),
]

profilemela/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.homepage, name="home"),
	path('', views.portfolio, name="portfolio"),
	path('', views.signup, name="signup")
]

story5/urls.py
from django.urls import path
from . import views

app_name ="story5"

urlpatterns = [
    path('form', views.buat_jadwal, name="schedule"),
    path('listform', views.daftar_jadwal, name="list_schedule"),
    path('deleteschedule', views.hapus_jadwal, name='hapus_jadwal'),
]

profilemela/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
	date = models.DateTimeField()
	place = models.CharField(max_length=100)
	event = models.CharField(max_length=100)
	category = models.CharField(max_length=30)

story5/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
	class Meta:
		model = Schedule
		fields = ('date', 'place', 'event','category')

profilemela/views.py
from django.shortcuts import render
from django.http import HttpResponse

def homepage(request):
	return render(request, "story_3.html", {})
def portfolio(request):
	return render(request, "story_3_pg2.html", {})
def signup(request):
	return render(request, "challenge_3.html", {})

# Create your views here.

story5/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Schedule
# Create your views here.

def daftar_jadwal(request):
    schedules = Schedule.objects.all().values()
    return render(request, 'JadwalMela.html', {'schedules': schedules})

def buat_jadwal(request):
    if request.method == "POST":
        form = ScheduleForm(request.POST)
        if form.is_valid():
            new_sch = form.save()
            new_sch.save()
            return redirect('story5:list_schedule')
    else:
        form = ScheduleForm()
    return render(request,'DaftarJadwal.html', {'form': form})

def hapus_jadwal(request):
	schedule = Schedule.objects.all().delete()
	return render(request, 'JadwalMela.html', {'schedules': schedule})

profilemela/templates/challenge_3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

    <title>User's Information</title>

  </head>
  <body>
    <div class="user-information">
        <p>User's Information</p>
    </div>
    <div class="container">
         <form>
            <div class="form-group">
                <label for="usr">Name:</label>
                <input type="text" class="form-control" id="usr">
            </div>
            <div class="form-group">
                <label>Date of Birth</label>
                <input type="date" class="form-control" id="exampleInputDOB1" placeholder="Date of Birth">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Email Address</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="validationDefaultUsername">Username</label>
                <input type="text" class="form-control" id="validationDefaultUsername" placeholder="Username" aria-describedby="inputGroupPrepend2" required>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="control-label">Password</label>
                <div class="form-inline row">
                    <div class="form-group col-sm-6">
                        <input type="password" data-minlength="6" class="form-control" id="inputPassword" placeholder="Password" required>
                        <div class="help-block">Minimum of 6 characters</div>
                    </div>
                    <div class="form-group col-sm-6">
                        <input type="password" class="form-control" id="inputPasswordConfirm" data-match="#inputPassword" data-match-error="Whoops, these don't match" placeholder="Confirm" required>
                        <div class="help-block with-errors"></div>
                    </div>
                </form>
            </div>

            <button class="btn btn-primary" type="submit">Submit</button>	
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

profilemela/templates/navbar1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape"> </div>
  	<div class="button">
  		<a href="portfolio" title="See Khameela's Portfolio">see my portfolio</a>
  	</div> 
  </body>
</html>

profilemela/templates/navbar2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape2"></div>
    <div class="button2">
        <a href="signup" title="New User? Sign Up Here!">sign up</a>
    </div>
  </body>
</html>

profilemela/templates/navbar3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape"> </div>
    <div class="button">
        <a href="homepage" title="Back to Khameela's Profile">back to profile</a>
    </div>
  </body>
</html>

profilemela/templates/navbar4.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape3"></div>
    <div class="button3">
        <a href="form" title="Make Schedule">make schedule</a>
    </div>
  </body>
</html>

profilemela/templates/navbar5.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape4"></div>
    <div class="button4">
        <a href="listform" title="See Schedule">see schedule</a>
    </div>
  </body>
</html>

profilemela/templates/story_3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">
    {% include "navbar1.html" %}
    {% include "navbar2.html" %}
    {% include "navbar4.html" %}
    {% include "navbar5.html" %}
    {% load static %}
    <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>

    <title>Khameela's Persona</title>
  </head>
  <body>
  	<div class="circle"> 
  		<img src="https://lh3.googleusercontent.com/VJ9_e1jly7iIolwaHg1iCgzBwWZdyvhB0yuOVhJkQ6cQlrPt4tnFvKAZCJegzLB-CvI2UCvij9CcKxZg66-IYti-7ZiirSnqZDZ6dMQIgNfWURY_NjTcyV2iJejlRDApvmZv7g8QxJfTb98rRI4_VTXTs2DjIwahoCIq6hQqJh-RcwZRuKYMeOb6eyjSRW1sR-pjzVTdPbH9uTP9Ggqkurvbk0s0O0YC9hSN5Wr3BVPciKXa7kqHLJGAP3eCK20sn5y4T_Y2dXFy82_epbJWDdb08qU6Cxi5gmkdowxNtd5hsYckS6N7QbmU_x7OZRWZiqu8KKk9p_WJMMM0kvdOAGkbGW-fGRX3NoLm9N5Kkx9lqIc79DpM33rDVwBHYPxdTLi-C7ZratQPQhGtXEMjahQ637_sHX_d0QaZaFDYZDZlrIxqnPvRcV1lzvuUUWTPpWAPxMuhv3c-ce4ogbz8TDDXaagrfcx0tbdst_9djiYhk92dtjoH4jJ2t-ODnVXVWHfFHERTV3D5YzmPsGCebGObtx0Lu3IE7R6KON1j9vsUoXuwt7wwoqmGMQnftPG_Oo1Px9B0eNJAEFhqACU_GfV9DtqjrE-GncDXScMxoaNjG1VaWlyEe3K67ieUAw=w366-h360-no" alt="Khameela Rahmah" class="foto-profile" style="max-width:100%;height:auto;">
  	</div>
  	<div class="name">
    	<p>Khameela Rahmah</p>
    </div>
    <div class="nickname">
    	<p>Graphic Design Enthusiast</p>
    </div>
    <div class="icon">
        <a href="mailto:rkhameela@gmail.com" target="_blank" title="Send Khameela an E-mail">
            <img src="https://lh3.googleusercontent.com/_eOjPl9UlHiyt7ybuYnxBVoqc5JePhm1aFAopteQD8biXbhdZfO-94eIWo6LflXX-RZOmgQidKgmLV5lndVaeinUtqyp-hPg41SHTjN7DjIwVcrJBSeBtCYWkOc3ExHQQG88XYHQVt5mK5p8oo2hUQi6yO4BlqbIEKGd4UsS1-jvRbE5mX5Mh1FFjW38rPpZlWZu_n4tuxdAR7PTKMiRJanOHbnuJcT12yo_xKQqZVEmbd9TM_cp3BSIPxshvosq_4RU3qwfR4CB99qiYKt6mmWSTJbfZFYAYdWqp4-axgkWoOCeathMJmMZrm8bUiGJ8l9sSZ2Seh6hlbQpHmSExQ7NC48vK1Q5kbZBs2Ny0l9FFKwqwyzLH1nbDz5hdGGRF0NqVzC3HuSVCVlLrnWXuEiqoDAvMYfHtiRxF8B-zaRXwyxlhkSjD7Ecx_I1wM3sQ5tNs9SsvL75I2vFDkuH2iwWrhiOd2XPXRGWg_wPjW60p0VD_jh6Na1iCQlOa9R6WdaGyxyK6rS6GE7fSj8N9WWz4JzgsaJ17MJ6GVs2IuTp3-_RxvTM1-QDOLjnM2Qtjs6ey5soAuOpK1_keEVrDJKmOPQUd4nCO9zcnuoP3QiHpz0BDcwVqbAWd6dBWQ=s512-no" alt="mailto:rkhameela@gmail.com" class="logo-email" style="max-width:100%;height:auto;">
        </a>
        <a href="https://twitter.com/melarhmh" target="_blank" title="See Khameela's Twitter page">
            <img src="https://lh3.googleusercontent.com/OgKz0hsFiAVd9LpY1cBlb__l_a89y7Rctp4SvnObrdegd4wd7HD15ZUWojZp7Le69Wp4acofT_6_uXX7x32PlgBh9TX_xq4Bqkr42nwdZG5xni4nuJX772dFW-iStPTrUykXBACOypvLKNuYvkKavliMYnZqiVoYcuUHDOlkx-RNiaQ86iJCyfDO9mDQT-Rm9-WEMbTaqkiCZXH2NjGwNjybUQunMPqjd-xvdBMpt15Hr6vQu3IJY8m_fYKW6erp01musdCF9cPjM0cmeAJuDwNtnSGTFF7ghd11jPBR5ybh74QFqF1VekFLCuwc9HLoyKuAPosAxQgGMTfDf2S0SnkLjHCt1mnOSO4DRxvguz8UEdEOf-0BjpWBeqZgDzbwUe8dHg5uqK_RuFrUqg0fOGYjUK5bTENB6TxZYxFNA6YJaLojN_cXd8nvSftEQuBG1dqMv6qeF2kLtw1WYM64dgfHaSb7H3wHk2Ffw2FfkAdCJ2yPwEaY5aldKFB6eU36P_a9Wo1ingq6hAmuUwRbuDg07zlV5eX7CJzdgB20JBvS6DIAHRmZtvvTFo-gYdMhjGC4Xad8wwYteirzPUOptrtno2glBauJ4TAH-qK4aWVYROSiB6ySbMnGeAaWhQ=s512-no" alt="twitter.com/melarhmh" class="logo-twitter" style="max-width:100%;height:auto;">
        </a>
        <a href="https://instagram.com/melarhmh" target="_blank" title="See Khameela's Instagram page">
            <img src="https://lh3.googleusercontent.com/U3eC7Ws2Emkazu9OrC2uew6LTRPbhBeaKc-o1VeSGZLqsTHIMOCgcHEgX9k0v9kmKKggd-8kydvqIL0yM_KAlCxjUMSl4q2gDDzcdZnD0_1uJnLvj4jxslzAn21irXjfzHFxyKGKzTa_n_nUzA7WvPwOmpIul1llVSM6asbs1LDv-2BzPf_uaqAK9bv0mVTn-1-6qqInbDvFg6Tbp-fvsvy327C3OdC2MkX3cQkQSA_7rI1KLvKh-kQyi8H0ceklVgT2p4qbOmSw77bAT_x-9W6iFHKp3i8algdb_6VrIR8weSFswVPU4jpST85JhkneNNfpaSyzHjDhzSpul9Ya_CBvXthPHualAApzTTOq1ZpOBVku93ewJ1SqRe1HNeKp4SSkRpoK5ObbUHwvRnipBjnLj8xBbEx7CQUI3CkabOKdvTeJyExX4VNzGGhws4FUBoeg95MmEGmAgCvWcpcXF-3zYKgLglSW9i7enxI_x_9GnboN2vKR8PDlUQICxgwezlChosl1Fp3w2NPRMwUFrrP-MVjY6bOpB9sCffN8kVR4TKYVZFxWE1EvkYnBCf9OZ5R6SoeLTNfl4swI8f-OXQY3-1922HV5De0lRZdwuTUNTpYyPktH2nDsM58eRA=s512-no" alt="instagram.com/melarhmh" class="logo-instagram" style="max-width:100%;height:auto;">
        </a>
        <img src="https://lh3.googleusercontent.com/UzTUbROfvDOkwVOq1fTQOPhkOT4WfvVJmqDlKKKKSUOMSvLS13mY4nE5O-_17i0WZI3ib6AKICP2R1VO4CF4yHvvHGiy3E8qvqmmde6A0D4_riJ9nubLVTjdjpGck7C2R9yZEhOOmqC9ax9Xf7MUmKoZWuyrtQOzfjNEIq4848_FzOyCswQxobls_-Kjpdguo5kM6yY9ZTZFYtrpoIYXZHgT3FRr0jQbTxas9o_2ZdMpqLO8QbIUxKTjKgL_SOXFp_4DDliOrB27UynQK72-aoW55RkTuV8hKwJQpxSGlt4fdPYkdyUNKq0IRvyjCn0C347CXM-7EvJugoSqBQjrYph-5On3GVtiaImqBF3yM91Z2YVnFtc70PB2otN-NS6M0H2PIYjQXIvqLS_kbXjwZv6F7WDAg33u06umno9ncuaq5dooLRNxvx93AKH-oQgy1f2gPjMnFBZfuAXNAMgeiwK2hRyagZGMPRHgALn-iJ7S31FPdpKzLPe12h3flzZACSB9Gta7ZdR-ncaqJUy5R-mQdB7f5pRRsK3e_pRdz2M5IgrYa4X7iunqCUf_o6nHgqZ9jRJKtbq4_zLWrOqAofASM2VHCICs1NN5BIdh5EqSY2fkYZtinXXZmuN0GQ=s512-no" alt="formal education" class="logo-education" style="max-width:100%;height:auto;">
        <img src="https://lh3.googleusercontent.com/oQliSuBDB4ZsyX9uJYH4maR0WzPypFvqyNhcTWGLBwurxvYHkgmrLXU6jXJJQqmaj6BnvVFLKjdBS3G1XfoveO6fN9uVkgxhMNwXFK08LlL90lU8ThzOlUyjzaKLGUWGB4LJLvQWZ30zafSJbnOJMgj02fLSx9QHSjj095eKKlTu785wzO6eTiGPVnOTeC6tpQbdZb38lyeD1JJP7aUeKEDRKJT3hRieuwYKek3kLFQ_vkd5dpqEHmuGDn3Djel5IICRA_ovDH1loTdhkUlqOWEk8x7zLpLnbXHw2P85ozQc-st93_tnYwFZtFI8WAU6X3bJLy5WjlTEeLhG5feUsNbjlG02M1QXfCmJ_lukluuDSeyjmyErtTxIXk60JyNtGlEtYSIHiv6VE5PJCKwpc9ifp-J7hCwaqeL27H_iYX1v9WN1-ITEpG-O6PVPcm-W2ws02BcABmZiYwEuQgzK7PgqSr_eTtiOGfsgqxksBFey2FDAlekViMV42yrDKE1rMLhf-3wopeGp0soC7ni6hqtaZVOV49HJAG-3iMecckUJwWvvNVW7adjqNLPV7ZryHOdknRh2m9UhkBWeP9iiRBAhzA0J-9mw76MGcpmfSQjAnBQKtF8QVALR8TH1XQ=s512-no" alt="experiences" class="logo-experiences" style="max-width:100%;height:auto;">
        <img src="https://lh3.googleusercontent.com/QHgFvvJtZ5XWfZNwiIZq3p5rh9JTNW5z6W5N9Ye2xSfOjWovcHLa_6j3AmIeXb7xIYhEOT4caJGXPBuEyGg6mtbEovRog97MOVYW7869uLuJekGeqM4Tm0aJyM72m2bsT6Y9k22gnoImZUm8_JzjVK3Qa73C2CNq_cQbE6xckJ5tihUGS6GnqWLgsa4HYXnVshv77EZJHuiRjehEmZOoAXrKRNTVvffB4hsRkS_el_jN0v4oJ1cgijOw0BBLFJPq3pJZrkedYkVHtCXs4-yLrP1aJIL4XKPxfSw7jtUqYV5KQaTJ1fTu76eYKd_fB7P6j33RDysy_FnCg1I82LzJb8EPhCEFqyl4Y_7hZY5jNVRA7s-jh7eW2lZWZoKjHTpIMM2iYqj147FWfMLR26LgZP-L3upK4I8oeI0pN2FAjmBcUOhQoj78ZN7oJFczQnmx5WLSPNbSRUfWolW01zpGzkImUMVQU8ocIs6nXbcjdefQEGCZWuWitPSmynRl9cRgDUdRNMsSXV48fxJJaAfGJREVrkhLeJMso2GamVB-GLdzplvWz3QQUhQRxsj2KyU23bFVApVRvOT110BWXScioDsbKWjqzW5Buscav-wxhqCAw760vTnIy1SO8XT2aQ=s512-no" alt="skills" class="logo-skills" style="max-width:100%;height:auto;">
    </div>
    <div class="rectangle"> </div>
    <div class="desc">
    	<h1>Get to Know Me</h1>
    	<p>Welcome to my profile! My name is Khameela Rahmah. I am currently a student at Faculty of Computer Science Universitas Indonesia. My passion is Digital Design. I hope I can be a professional UI/UX Designer in the future.</p>
    </div>
    <div class="formal-education">
    	<p>Formal Education</p>
    	<ul style="list-style-type:none">
            <li>SDN Dukuh 09 Pagi</li>
            <li>SMPN 49 Jakarta</li>
            <li>SMAN 39 Jakarta</li>
            <li>Universitas Indonesia</li>
        </ul> 
    <div class="experiences">
        <p>Experiences</p>
        <ul style="list-style-type:none">
            <li>Staff of Biro Media BEM Fasilkom UI 2018</li>
            <li>Staff of LO Wisuda Ganjil 2018</li>
            <li>Staff of Event Wisuda Genap 2018</li>
            <li>Staff of Decoration CGT 2018</li>
            <li>Staff of Creative OH Fasilkom UI 2018</li>
            <li>Staff of Press COMPFEST X</li>
            <li>Staff of HPK PMB 2018</li>
        </ul>
    <div class="circle-skills1"> </div>
    <div class="circle-skills2"> </div>
    <div class="special-skills">
        <p>Special Skills</p>
    </div>
    <div class="special-skills1">
        <p>Digital Design</p>
        <pre>4/5</pre>
    </div>
    <div class="special-skills2">
        <p>Digital Writing</p>
        <pre>3.5/5</pre>
    </div>

    <div id="nav-placeholder1"></div>
    <script>
    	$(function) {
    		$("#nav-placeholder1").load("navbar1.html");});
    	}
    </script>

    <div id="nav-placeholder2"></div>
    <script>
    	$(function) {
    		$("#nav-placeholder2").load("navbar2.html");});
    	}
    </script>
    <div id="nav-placeholder4"></div>
    <script>
        $(function) {
            $("#nav-placeholder4").load("navbar4.html");});
        }
    </script>
    <div id="nav-placeholder5"></div>
    <script>
        $(function) {
            $("#nav-placeholder5").load("navbar5.html");});
        }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

story5/templates/JadwalMela.html
<!DOCTYPE html>
<html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<body>
    <div class=title> 
        <h1>Schedule List</h1>
    </div>

    <div class="row">
        <div class="col-md-9"></div>
        <a href="{% url 'story5:hapus_jadwal' %}" type="button" class="btn btn-danger">Hapus Semua Jadwal</a>
    </div>

    {% for schedule in schedules %}

    <div>
        <p>Tanggal: {{ schedule.date }}</p>
        <p>Tempat: {{ schedule.place }}</p>
        <p>Event: {{ schedule.event }}</p>
        <p>Kategori: {{ schedule.category }}</p>
    </div>
    <br>
    {% endfor %}
</body>
</html>